# Generated by Django 3.2.8 on 2021-12-31 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='moon_sign',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='rising_sign',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='sun_sign',
            field=models.CharField(default='', max_length=50),
        ),
    ]
