# Generated by Django 3.2.8 on 2021-12-31 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_auto_20211231_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateTimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='moon_sign',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='rising_sign',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='sun_sign',
            field=models.CharField(max_length=50),
        ),
    ]
