# Generated by Django 3.2.8 on 2021-12-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_appointment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(default=9999, on_delete=django.db.models.deletion.CASCADE, to='clients.client'),
        ),
    ]
