# Generated by Django 3.2.8 on 2021-12-31 19:48

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_appointment_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='clients.client'),
        ),
    ]
