# Generated by Django 3.2.8 on 2022-01-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_appointment_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='moon_sign',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='rising_sign',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='client',
            name='sun_sign',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
