# Generated by Django 3.2.8 on 2022-01-14 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_client_birth_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(max_length=50),
        ),
    ]
